"""add algo.notes and algo_run.archived

Revision ID: 19da5f1d4255
Revises: 37401bde569a
Create Date: 2026-06-09 15:10:03.109657
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19da5f1d4255'
down_revision: Union[str, None] = '37401bde569a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('algo', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
