"""add algo_run.trade_log

Revision ID: 1b856aa61865
Revises: b5fe280f771a
Create Date: 2026-06-06 21:36:17.632703
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b856aa61865'
down_revision: Union[str, None] = 'b5fe280f771a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_log', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.drop_column('trade_log')

    # ### end Alembic commands ###
