"""drop broker password and totp columns

Revision ID: 26c0bf987de5
Revises: 33150832cf97
Create Date: 2026-06-09 08:46:17.456754
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c0bf987de5'
down_revision: Union[str, None] = '33150832cf97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_account', schema=None) as batch_op:
        batch_op.drop_column('enc_password')
        batch_op.drop_column('enc_totp_secret')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_totp_secret', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('enc_password', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
