"""add broker_account.armed

Revision ID: 33150832cf97
Revises: 1b856aa61865
Create Date: 2026-06-08 11:01:15.722024
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33150832cf97'
down_revision: Union[str, None] = '1b856aa61865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_account', schema=None) as batch_op:
        batch_op.drop_column('armed')

    # ### end Alembic commands ###
