"""add algo_run.state for live recovery

Revision ID: 37401bde569a
Revises: 26c0bf987de5
Create Date: 2026-06-09 09:34:02.186911
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37401bde569a'
down_revision: Union[str, None] = '26c0bf987de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
