"""add algo_run.batch_id

Revision ID: 43291c1c119b
Revises: 19da5f1d4255
Create Date: 2026-06-09 16:15:03.459131
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43291c1c119b'
down_revision: Union[str, None] = '19da5f1d4255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_algo_run_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_algo_run_batch_id'))
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
