#!/usr/bin/env bash
#
# deploy-vps.sh — native (venv + systemd) bootstrap for the skas-algo backend on a Linux VPS
# (tested against an Ubuntu AWS Lightsail box). Re-runnable: on later runs it just pulls,
# rebuilds the UI, reinstalls deps, and restarts the service.
#
# It sets up ONLY the mechanical bits: system deps, venv, the built SPA, an .env with fresh
# secrets, the DB schema, and the systemd unit. It deliberately does NOT connect brokers, arm
# accounts, enable live trading, or place any order — every one of those is the owner's hand
# (see the "NEXT STEPS" it prints at the end, and docs/DEPLOY.md).
#
# Prereqs: run as your normal login user (NOT root) with sudo rights; the sibling data repo at
# ../skas-data; internet access. Usage:  ./scripts/deploy-vps.sh
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_REPO="$(cd "${REPO}/../skas-data" 2>/dev/null && pwd || true)"
RUN_USER="$(whoami)"
ENV_FILE="${REPO}/.env"
py() { "${REPO}/venv/bin/python" "$@"; }

say() { printf '\n\033[1;36m== %s ==\033[0m\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -ne 0 ] || die "run as your login user (with sudo), not root — files would be owned by root."
[ -n "${DATA_REPO}" ] || die "sibling ../skas-data not found. Clone it next to this repo first (it's the market-data layer, installed editable)."

# ---------------------------------------------------------------- 1. system packages
say "1/7 system packages (apt)"
if command -v apt-get >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y python3-venv python3-dev build-essential git rsync curl
  # Node for the frontend build (NodeSource keeps a current LTS; skip if node already present).
  if ! command -v node >/dev/null 2>&1; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
  fi
else
  warn "no apt-get — install python3-venv, build-essential, git, node/npm yourself, then re-run."
fi

# ---------------------------------------------------------------- 2. python venv + editable installs
say "2/7 python venv + editable installs (skas-data, skas-algo)"
[ -d "${REPO}/venv" ] || python3 -m venv "${REPO}/venv"
py -m pip install -q --upgrade pip
py -m pip install -q -e "${DATA_REPO}"
py -m pip install -q -e "${REPO}"

# ---------------------------------------------------------------- 3. build the SPA
say "3/7 build the web UI (npm run build → web/dist)"
( cd "${REPO}/web" && npm ci && npm run build )

# ---------------------------------------------------------------- 4. .env (generate ONCE, never clobber)
say "4/7 .env"
if [ -f "${ENV_FILE}" ]; then
  warn ".env already exists — leaving it untouched (secrets are never regenerated on a re-run)."
else
  echo "Creating ${ENV_FILE} with fresh secrets."
  FERNET="$(py -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"
  JWT="$(py -c 'import secrets; print(secrets.token_urlsafe(48))')"
  echo "Set the web-login password (used to sign in to the UI over Tailscale):"
  HASH_LINE="$("${REPO}/venv/bin/skas-algo" hash-password | grep '^SKAS_AUTH_PASSWORD_HASH=')"
  [ -n "${HASH_LINE}" ] || die "hash-password produced no hash line."
  umask 077
  cat > "${ENV_FILE}" <<EOF
# Generated by deploy-vps.sh on first run. Keep this file private (chmod 600).
SKAS_ENVIRONMENT=production
SKAS_DEBUG=false
# Bind localhost only — Tailscale (tailscale serve) fronts the public/tailnet TLS. NEVER 0.0.0.0 here.
SKAS_API_HOST=127.0.0.1
SKAS_API_PORT=8080
# Absolute path (the CWD-relative default silently opens a different empty DB).
SKAS_DATABASE_URL=sqlite:///${REPO}/skas_algo.db
# Backend serves the built SPA on the same origin as /api (single origin → wss just works).
SKAS_SERVE_WEBAPP=true
# Encrypts broker api_secret + daily token at rest. LOSING THIS makes stored creds unrecoverable.
SKAS_SECRET_ENCRYPTION_KEY=${FERNET}
# Auth is enforced only when BOTH are set — required on a networked host.
${HASH_LINE}
SKAS_AUTH_JWT_SECRET=${JWT}
# Real orders stay OFF until you deliberately flip this AND arm the account (owner's hand).
SKAS_LIVE_TRADING_ENABLED=false
# Off-box backup: uncomment + point at your bucket/host ({path}=abs snapshot, {name}=filename).
# SKAS_BACKUP_REMOTE_CMD=aws s3 cp {path} s3://YOUR_BUCKET/skas-backups/{name}
EOF
  chmod 600 "${ENV_FILE}"
  echo "Wrote ${ENV_FILE} (chmod 600). Back up SKAS_SECRET_ENCRYPTION_KEY somewhere safe."
fi

# ---------------------------------------------------------------- 5. DB schema / migrations
say "5/7 database schema (alembic upgrade head)"
( cd "${REPO}" && "${REPO}/venv/bin/alembic" upgrade head )

# ---------------------------------------------------------------- 6. systemd unit
say "6/7 systemd unit (skas-algo.service)"
UNIT_SRC="${REPO}/deploy/skas-algo.service"
UNIT_DST="/etc/systemd/system/skas-algo.service"
sed -e "s|@@USER@@|${RUN_USER}|g" -e "s|@@REPO@@|${REPO}|g" "${UNIT_SRC}" | sudo tee "${UNIT_DST}" >/dev/null
sudo systemctl daemon-reload
sudo systemctl enable --now skas-algo
sleep 2
sudo systemctl --no-pager --lines=0 status skas-algo || true

# ---------------------------------------------------------------- 7. next steps (owner's hand)
say "7/7 done — backend is up on 127.0.0.1:8080"
cat <<EOF

NEXT STEPS (yours — this script never touches brokers, arming, or orders):

  1. Front it with Tailscale (private HTTPS, no public exposure):
       sudo tailscale up                              # authenticate this VPS to your tailnet
       sudo tailscale serve --bg http://127.0.0.1:8080  # tailnet HTTPS at the root path
       tailscale serve status                         # shows the https://<vps>.<tailnet>.ts.net URL
     (serve needs root; or `sudo tailscale set --operator=\$USER` once to drop the sudo. If it
      errors on HTTPS certs, enable MagicDNS + HTTPS Certificates in the Tailscale admin console.)

  2. Open that URL on a device on your tailnet, log in with the password you just set.

  3. Connect the Satish Kite (Zerodha) account in the UI (Brokers page) and log in.
     Keep this account DEDICATED to the VPS — do not hand-trade it, and remove it from the
     Mac (a fresh Kite login supersedes the other machine's token).

  4. Deploy hni_weekly as PAPER first (quote_source=zerodha, Satish) to confirm it enters
     off the live chain. Only then: flip SKAS_LIVE_TRADING_ENABLED=true in .env, restart
     (sudo systemctl restart skas-algo), arm the account, and go-live with a tiny first order.

  Logs:    journalctl -u skas-algo -f
  Restart: sudo systemctl restart skas-algo
  See docs/DEPLOY.md for the full runbook + the constraints (Dhan can't place real orders yet).
EOF
