import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { brokers as brokerApi, portfolio as papi } from "../api/client";
import AllocationView from "../components/portfolio/AllocationView";
import BucketsView from "../components/portfolio/BucketsView";
import GoalsView from "../components/portfolio/GoalsView";
import GrowthView from "../components/portfolio/GrowthView";
import IncomeView from "../components/portfolio/IncomeView";
import HoldingModal from "../components/portfolio/HoldingModal";
import LedgerModal from "../components/portfolio/LedgerModal";
import OverviewView from "../components/portfolio/OverviewView";
import SeedModal from "../components/portfolio/SeedModal";
import { Kpi, Notice, Pill, Segments } from "../components/portfolio/primitives";
import RebalanceView from "../components/portfolio/RebalanceView";
import TaxView from "../components/portfolio/TaxView";
import {
  dayMove, money, pct, signedMoney, stampLabel, toInput,
  type BucketInput, type GoalInput, type Holding, type HoldingInput, type SyncReport,
} from "../lib/portfolio";

type Tab =
  | "Overview" | "Allocation" | "Growth" | "Income" | "Goals" | "Buckets" | "Rebalance" | "Tax";
const TABS: Tab[] = [
  "Overview", "Allocation", "Growth", "Income", "Goals", "Buckets", "Rebalance", "Tax",
];

/** Per-device view preferences. These are genuinely per-device (a phone wants compact rows,
 * the desk does not), so they stay in the browser rather than the shared DB. */
function usePref<T extends string>(key: string, fallback: T): [T, (v: T) => void] {
  const [v, setV] = useState<T>(() => {
    try {
      return (window.localStorage.getItem(key) as T) ?? fallback;
    } catch {
      return fallback;
    }
  });
  return [
    v,
    (next: T) => {
      setV(next);
      try { window.localStorage.setItem(key, next); } catch { /* private mode */ }
    },
  ];
}

export default function PortfolioPage() {
  const qc = useQueryClient();
  const [tab, setTab] = useState<Tab>("Overview");
  const [density, setDensity] = usePref<"comfortable" | "compact">(
    "portfolio.density", "comfortable",
  );
  const [includeRe, setIncludeRe] = usePref<"yes" | "no">("portfolio.includeRe", "yes");
  const [editing, setEditing] = useState<Holding | "new" | null>(null);
  const [ledger, setLedger] = useState<Holding | null>(null);
  const [sync, setSync] = useState<SyncReport | null>(null);
  const [seeding, setSeeding] = useState(false);
  const [dismissed, setDismissed] = useState(false);

  const { data, isLoading, error } = useQuery({
    queryKey: ["portfolio"],
    queryFn: papi.get,
    refetchInterval: 5 * 60_000,
  });
  const { data: accounts } = useQuery({ queryKey: ["brokers"], queryFn: brokerApi.list });

  const refresh = () => qc.invalidateQueries({ queryKey: ["portfolio"] });
  const onSuccess = () => { void refresh(); };

  const syncNow = useMutation({
    mutationFn: () => papi.sync(),
    onSuccess: (r) => { setSync(r); setDismissed(false); void refresh(); },
  });
  const refreshNavs = useMutation({ mutationFn: papi.refreshFunds });

  // Written out rather than generated by a helper: a factory that called useMutation would
  // be a rules-of-hooks violation that happens to work only while every call stays
  // unconditional — one early return away from breaking in a way React reports as a
  // different component's bug.
  const saveHolding = useMutation({
    mutationFn: ({ id, body }: { id: number | null; body: HoldingInput }) =>
      id === null ? papi.createHolding(body) : papi.updateHolding(id, body),
    onSuccess,
  });
  const removeHolding = useMutation({ mutationFn: papi.deleteHolding, onSuccess });
  const createBucket = useMutation({ mutationFn: papi.createBucket, onSuccess });
  const updateBucket = useMutation({
    mutationFn: ({ id, body }: { id: number; body: BucketInput }) => papi.updateBucket(id, body),
    onSuccess,
  });
  const removeBucket = useMutation({ mutationFn: papi.deleteBucket, onSuccess });
  const createGoal = useMutation({ mutationFn: papi.createGoal, onSuccess });
  const updateGoal = useMutation({
    mutationFn: ({ id, body }: { id: number; body: GoalInput }) => papi.updateGoal(id, body),
    onSuccess,
  });
  const removeGoal = useMutation({ mutationFn: papi.deleteGoal, onSuccess });
  const saveTargets = useMutation({
    mutationFn: (class_targets: Record<string, number>) => papi.saveTargets({ class_targets }),
    onSuccess,
  });
  const saveKindTargets = useMutation({
    mutationFn: (kind_targets: Record<string, number>) => papi.saveTargets({ kind_targets }),
    onSuccess,
  });

  // Real estate is lumpy, illiquid and revalued by guesswork — including it can swing every
  // allocation figure on the page. The toggle affects the WHOLE screen, so it lives here.
  const rows = useMemo(() => {
    const all = data?.holdings ?? [];
    return includeRe === "yes" ? all : all.filter((h) => h.asset_class !== "re");
  }, [data, includeRe]);

  const t = useMemo(() => {
    const value = rows.reduce((a, h) => a + h.value, 0);
    const invested = rows.reduce((a, h) => a + h.invested, 0);
    const byKind: Record<string, number> = {};
    for (const h of rows) byKind[h.kind] = (byKind[h.kind] ?? 0) + h.value;
    for (const k of Object.keys(byKind)) {
      byKind[k] = value > 0 ? (byKind[k] / value) * 100 : 0;
    }
    return {
      value,
      invested,
      gain: value - invested,
      gainPct: invested > 0 ? ((value - invested) / invested) * 100 : 0,
      day: dayMove(rows),
      blended: value > 0
        ? rows.reduce((a, h) => a + (h.xirr_pct ?? 0) * h.value, 0) / value
        : 0,
      mix: byKind,
      auto: rows.filter((h) => h.sync === "auto").length,
      manual: rows.filter((h) => h.sync === "manual").length,
    };
  }, [rows]);

  const lastSync = useMemo(() => {
    const stamps = rows.map((h) => h.last_synced_at).filter(Boolean) as string[];
    return stamps.length ? stamps.sort().slice(-1)[0] : null;
  }, [rows]);

  const brokerOptions = useMemo(
    () => (accounts ?? []).map((a) => ({ id: a.id, label: a.label, broker: a.broker })),
    [accounts],
  );

  if (error) {
    return (
      <div className="mx-auto max-w-[1340px] px-4 py-8 sm:px-8">
        <Notice tone="warn">
          Couldn't load the portfolio — the backend isn't responding. Start it
          (<code>skas-algo</code> on :8080) and this page will fill in.
        </Notice>
      </div>
    );
  }

  // With five tags a ratio string ("55 : 25 : 10 : 7 : 3") is unreadable in a tile, so this
  // card answers the question the mix is actually for — how much risk am I carrying, and how
  // far is that from what I chose. The full breakdown lives in Allocation and Rebalance.
  // ?? 0, because this runs on the FIRST render too — before the fetch resolves, `rows` is
  // empty, so no tag has a value and `t.mix.equity` is undefined. `.toFixed()` on that threw
  // before anything painted, which reads as "the page doesn't load" rather than as an error.
  const equityShare = t.mix.equity ?? 0;
  const equityTarget = data?.kind_targets.equity ?? 0;
  const equityDrift = equityShare - equityTarget;

  return (
    <div className="mx-auto max-w-[1340px] px-4 pb-[72px] pt-[26px] sm:px-8">
      <div className="mb-4 flex flex-wrap items-center gap-3.5">
        <h1 className="m-0 text-[27px] font-bold [font-family:'Space_Grotesk',system-ui,sans-serif] text-[var(--strong)]">
          Portfolio
        </h1>
        {/* A status pill that happened to be clickable read as decoration — the one action
            that makes every number on the page current has to look like a button. */}
        <button
          onClick={() => syncNow.mutate()}
          disabled={syncNow.isPending}
          title="Refresh every live price: broker quotes for equities and ETFs, AMFI NAVs for funds, and the US / crypto feed. Hand-entered holdings keep the value you typed. Also records today's history point."
          className="inline-flex items-center gap-2 rounded-[11px] bg-[var(--accent)] px-[18px] py-2.5 text-[13.5px] font-extrabold text-white disabled:opacity-60"
        >
          <span className={syncNow.isPending ? "animate-spin" : ""}>⟳</span>
          {syncNow.isPending ? "Refreshing…" : "Refresh prices"}
        </button>
        <span
          className="inline-flex items-center gap-[7px] rounded-full border-[1.5px] border-[var(--tint-border)] bg-[var(--tint)] px-3.5 py-2 text-[12.5px] font-extrabold text-[var(--accent-deep)]"
          title={lastSync ? "When a live price was last written" : "Nothing has been priced yet"}
        >
          <span
            className="inline-block h-[7px] w-[7px] rounded-full"
            style={{ background: lastSync ? "var(--pos)" : "var(--faint)" }}
          />
          {lastSync ? stampLabel(lastSync) : "never priced"}
        </span>
        <Pill title="Auto holdings refresh from a broker or AMFI. Manual ones keep what you typed.">
          {t.auto} auto · {t.manual} manual
        </Pill>

        <div className="ml-auto flex flex-wrap items-center gap-2.5">
          <button
            onClick={() => refreshNavs.mutate()}
            disabled={refreshNavs.isPending}
            title="Pull today's AMFI NAV file on its own. 'Refresh prices' already does this — you need it separately only to search for a fund before adding it."
            className="rounded-[11px] border-[1.5px] border-[var(--field-border)] px-3.5 py-2 text-[12.5px] font-extrabold text-[var(--muted)] disabled:opacity-60"
          >
            {refreshNavs.isPending ? "Fetching…" : "NAV file"}
          </button>
          <button
            onClick={() => setSeeding(true)}
            title="Paste your tracking spreadsheet to create holdings and load their full buy/sell history at once."
            className="rounded-[11px] border-[1.5px] border-[var(--field-border)] px-3.5 py-2 text-[12.5px] font-extrabold text-[var(--muted)]"
          >
            Import sheet
          </button>
          <button
            onClick={() => setEditing("new")}
            className="rounded-[11px] border-[1.5px] border-[var(--accent)] px-[18px] py-2.5 text-[13.5px] font-extrabold text-[var(--accent-deep)]"
          >
            + Add holding
          </button>
        </div>
      </div>

      {refreshNavs.data && (
        <div className="mb-3.5">
          <Notice>
            {refreshNavs.data.schemes.toLocaleString("en-IN")} schemes loaded, NAVs as of{" "}
            {refreshNavs.data.as_of}
            {refreshNavs.data.stale_days != null && refreshNavs.data.stale_days > 1 && (
              <> — {refreshNavs.data.stale_days} days old. AMFI publishes after the close, so
                one day behind is normal; more means the feed is stuck.</>
            )}
            {!refreshNavs.data.has_previous && (
              <> · no earlier file cached yet, so fund day-changes read zero until tomorrow.</>
            )}
          </Notice>
        </div>
      )}

      {sync && !dismissed && (
        <div className="mb-3.5">
          <Notice tone={sync.issues.length ? "warn" : "info"}>
            <div className="flex items-start gap-3">
              <div className="flex-1">
                Synced {sync.counts.updated} holding{sync.counts.updated === 1 ? "" : "s"}.
                {sync.issues.length > 0 && (
                  <ul className="mt-1 list-disc pl-5 font-semibold">
                    {sync.issues.slice(0, 6).map((i, n) => (
                      <li key={n}><strong>{i.holding}</strong> — {i.reason}</li>
                    ))}
                  </ul>
                )}
                {sync.discovered.length > 0 && (
                  <div className="mt-1 font-semibold">
                    Your broker also holds{" "}
                    {sync.discovered.map((d) => `${d.symbol} (${d.units})`).join(", ")} — not
                    tracked here. Add them if you want them counted.
                  </div>
                )}
              </div>
              <button onClick={() => setDismissed(true)} className="font-extrabold opacity-70">
                ✕
              </button>
            </div>
          </Notice>
        </div>
      )}

      <div className="mb-4 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">
        <Kpi
          label="NET WORTH" value={money(t.value)}
          sub={`across ${rows.length} holding${rows.length === 1 ? "" : "s"}`}
          help="Current value of everything tracked here. The number to watch monthly, not daily."
        />
        <Kpi
          label="INVESTED" value={money(t.invested)} sub="total cost basis"
          help="Money you actually put in, net of what partial sales returned. Gain is net worth minus this."
        />
        <Kpi
          label="UNREALIZED GAIN" value={signedMoney(t.gain)}
          valueColor={t.gain >= 0 ? "var(--pos)" : "var(--danger)"}
          sub={`${pct(t.gainPct)} on cost`}
          help="Paper profit across all holdings. The Tax tab shows what selling today would cost."
        />
        <Kpi
          label="RETURN · BLENDED" value={pct(t.blended)}
          valueColor={t.blended >= 0 ? "var(--pos)" : "var(--danger)"}
          sub="value-weighted"
          help="Annualised return weighted by holding size. Above ~12% beats inflation plus an FD comfortably; 8-12% is fine; below 8% is debt-like returns for equity-like risk."
        />
        <Kpi
          label="TODAY"
          value={t.day.rupees === 0 ? "—" : signedMoney(t.day.rupees)}
          valueColor={t.day.rupees > 0 ? "var(--pos)"
            : t.day.rupees < 0 ? "var(--danger)" : "var(--faint)"}
          sub={t.day.pct === null ? "market-linked only"
            : `${pct(t.day.pct, 2)} · market-linked only`}
          subColor={t.day.pct === null ? "var(--faint)"
            : t.day.pct >= 0 ? "var(--pos)" : "var(--danger)"}
          help="Today's move in holdings that actually reprice. The percentage is measured against those holdings' value yesterday — EPF, PPF and hand-entered items are left out of it, or a still portfolio would look calmer than it was. A fund's NAV is a day behind by design."
        />
        <Kpi
          label="EQUITY SHARE"
          value={`${equityShare.toFixed(0)}%`}
          sub={Math.abs(equityDrift) < 1
            ? `on target (${equityTarget.toFixed(0)}%)`
            : `${equityDrift > 0 ? "+" : ""}${equityDrift.toFixed(0)} pts vs ${equityTarget.toFixed(0)}% target`}
          subColor={Math.abs(equityDrift) < 1 ? "var(--pos)"
            : equityDrift > 0 ? "var(--note)" : "var(--accent-deep)"}
          help="How much of the book carries equity risk, against the target you set. This is the single number that decides how a bad year feels. The full five-tag breakdown is on Allocation, and Rebalance says what to move."
        />
      </div>

      <div className="mb-4 flex flex-wrap items-center gap-3">
        <div className="overflow-x-auto">
          <Segments value={tab} onChange={setTab} options={TABS.map((x) => ({ value: x, label: x }))} />
        </div>
        <div className="ml-auto flex items-center gap-2 text-[11.5px] font-bold text-[var(--faint)]">
          <button
            onClick={() => setDensity(density === "compact" ? "comfortable" : "compact")}
            title="Row height in the holdings table"
            className="rounded-lg px-2 py-1 hover:text-[var(--strong)]"
          >
            {density === "compact" ? "Compact rows" : "Comfortable rows"}
          </button>
          <button
            onClick={() => setIncludeRe(includeRe === "yes" ? "no" : "yes")}
            title="Property is lumpy, illiquid and revalued by guesswork — excluding it shows the mix of money you can actually move."
            className="rounded-lg px-2 py-1 hover:text-[var(--strong)]"
          >
            {includeRe === "yes" ? "Incl. property" : "Excl. property"}
          </button>
        </div>
      </div>

      {isLoading || !data ? (
        <div className="py-16 text-center text-[13px] font-semibold text-[var(--faint)]">
          Loading portfolio…
        </div>
      ) : rows.length === 0 && tab !== "Overview" ? (
        <Notice>Add a holding first — every other tab derives from them.</Notice>
      ) : (
        <>
          {tab === "Overview" && (
            <OverviewView
              rows={rows} payload={data} density={density}
              onEdit={setEditing} onLedger={setLedger}
              onDelete={(h) => removeHolding.mutate(h.id)}
            />
          )}
          {tab === "Allocation" && <AllocationView rows={rows} payload={data} />}
          {tab === "Growth" && (
            <GrowthView rows={rows} payload={data} buckets={data.buckets} />
          )}
          {tab === "Income" && (
            <IncomeView
              rows={rows} payload={data} onChanged={refresh}
              onSetYield={(h, yieldPct) =>
                saveHolding.mutate({
                  id: h.id, body: { ...toInput(h), dividend_yield_pct: yieldPct },
                })}
            />
          )}
          {tab === "Goals" && (
            <GoalsView
              rows={rows} payload={data}
              onCreate={(g) => createGoal.mutate(g)}
              onUpdate={(id, body) => updateGoal.mutate({ id, body })}
              onDelete={(id) => removeGoal.mutate(id)}
            />
          )}
          {tab === "Buckets" && (
            <BucketsView
              rows={rows} buckets={data.buckets}
              onCreate={(b) => createBucket.mutate(b)}
              onUpdate={(id, body) => updateBucket.mutate({ id, body })}
              onDelete={(id) => removeBucket.mutate(id)}
              onSetExcluded={(h, excluded) =>
                saveHolding.mutate({
                  id: h.id,
                  body: { ...toInput(h), excluded_from_buckets: excluded },
                })}
            />
          )}
          {tab === "Rebalance" && (
            <RebalanceView
              rows={rows} payload={data}
              onSaveTargets={(targets) => saveTargets.mutate(targets)}
              onSaveKindTargets={(targets) => saveKindTargets.mutate(targets)}
            />
          )}
          {tab === "Tax" && <TaxView rows={rows} payload={data} />}
        </>
      )}

      {editing && data && (
        <HoldingModal
          holding={editing} payload={data} brokers={brokerOptions}
          onClose={() => setEditing(null)}
          onSave={(body) => {
            saveHolding.mutate({ id: editing === "new" ? null : editing.id, body });
            setEditing(null);
          }}
        />
      )}

      {seeding && data && (
        <SeedModal
          payload={data} brokers={brokerOptions}
          onClose={() => setSeeding(false)}
          onSeeded={refresh}
        />
      )}

      {ledger && (
        <LedgerModal
          holding={rows.find((h) => h.id === ledger.id) ?? ledger}
          onClose={() => setLedger(null)}
          onChanged={refresh}
        />
      )}
    </div>
  );
}
